### PR TITLE
Add a method in document for creating a section...

### PR DESCRIPTION
**Pull request by orgads**
... if it doesn't exist.

### CODE REVIEW

**Comment by orgads** [comment]
I'd even consider doing this by default for [], similar to IniFile, and perl's Config::Tiny.

What do you say?

**Comment by antw** [comment]
Thank you, and sorry for taking so long to merge this. I have released 1.4.2 with your changes.

**Comment by orgads** [comment]
What about my suggestion?

**Comment by antw** [comment]
I don't think calling `a_document[section]` should create a blank section; that wouldn't be compatible with `Hash#[]`, which returns nil when no such key exists.

On the other hand, I quite like the idea of doing something with `Document#[]=` to make it easier to create new sections. Maybe something like this?

```ruby
document[section] = { key1: val1, key2: val2 }
```

**Comment by orgads** [comment]
Looks great. If you implement that, remove the section method I added here since it won't be needed.

**Comment by orgads** [comment]
Actually not, leave it. It enables easy creation of sections without having the data first.

**Pull request merged**
